version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: ntb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ntb
      POSTGRES_PASSWORD: ntb_pass
      POSTGRES_DB: ntb_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ntb -d ntb_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ntb-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # AMQP (для кода)
      - "15672:15672" # Web UI (для браузера)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: